// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZb-8lHoYHpmV9SLqKwSIFP_-JLXeeb8s',
    appId: '1:419265499367:web:e9b234c7433a67978d1242',
    messagingSenderId: '419265499367',
    projectId: 'homiezy-44936',
    authDomain: 'homiezy-44936.firebaseapp.com',
    storageBucket: 'homiezy-44936.firebasestorage.app',
    measurementId: 'G-08MVC2QCYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN2oFLvQdgn8ga8Pz8KOtoMhYRAIGLX2A',
    appId: '1:419265499367:android:63243319531221d08d1242',
    messagingSenderId: '419265499367',
    projectId: 'homiezy-44936',
    storageBucket: 'homiezy-44936.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvYA7wPwjT8U7Bbj9KsQUzyQ8R1yiWViE',
    appId: '1:419265499367:ios:7a558047facdf4728d1242',
    messagingSenderId: '419265499367',
    projectId: 'homiezy-44936',
    storageBucket: 'homiezy-44936.firebasestorage.app',
    androidClientId: '419265499367-gcfn9gnep1sgu0581clj70jrkm7dlstf.apps.googleusercontent.com',
    iosClientId: '419265499367-gn4hls1dj4qr9bo4h77rgafk5kiai6n6.apps.googleusercontent.com',
    iosBundleId: 'com.example.homiezy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvYA7wPwjT8U7Bbj9KsQUzyQ8R1yiWViE',
    appId: '1:419265499367:ios:7a558047facdf4728d1242',
    messagingSenderId: '419265499367',
    projectId: 'homiezy-44936',
    storageBucket: 'homiezy-44936.firebasestorage.app',
    androidClientId: '419265499367-gcfn9gnep1sgu0581clj70jrkm7dlstf.apps.googleusercontent.com',
    iosClientId: '419265499367-gn4hls1dj4qr9bo4h77rgafk5kiai6n6.apps.googleusercontent.com',
    iosBundleId: 'com.example.homiezy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZb-8lHoYHpmV9SLqKwSIFP_-JLXeeb8s',
    appId: '1:419265499367:web:1cac1cbff9a8eabe8d1242',
    messagingSenderId: '419265499367',
    projectId: 'homiezy-44936',
    authDomain: 'homiezy-44936.firebaseapp.com',
    storageBucket: 'homiezy-44936.firebasestorage.app',
    measurementId: 'G-KMFNXELT0C',
  );
}
